ruby/homework/blog/config/routes.rb
Rails.application.routes.draw do
  get "authors/new"
  get "authors/create"
  get "authors/show"
  get "authors/edit"
  get "authors/update"
  get "authors/destroy"
  devise_for :users
  get "donations/new"
  get "donations/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  



  resources :categories
    resources :authors

    resources :donations, only: [:new, :create]

    resources :articles do
      resources :comments, only: [:create, :destroy]  # Only allow create and destroy actions for comments
    end
    
  
  # Close the articles block
  # Close the categories block


  resources :donations, only: [:new, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "categories#index"
end

ruby/homework/blog/app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
end

ruby/homework/blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @categories = Category.all
  end

  def show
   
    @articles = @category.articles
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created!'
    else
      render :new
    end
  end

  def edit
    # The @category will be set by the before_action
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end
  
  

  private

  def set_category
    @category = Category.find(params[:id])
  end


  def category_params
    params.require(:category).permit(:name, :description)
  end

end

ruby/homework/blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

ruby/homework/blog/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit "Save Changes" %>
  </div>
<% end %>

ruby/homework/blog/app/views/categories/index.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>

<div id="categories-page">
  <h1>Categories</h1>
    <div id="category-card">
    <% @categories.each do |category| %>
      <div class="category-box">
        <div class="category-info">
          <%= link_to category.name, category_path(category), class: "category-title" %> <!-- Category name link -->
          <p class="category-description"><i><%= category.description %></i></p> <!-- Category description -->
          <p class="category-articles-count"><%= category.articles.count %> articles</p> <!-- Article count -->
        </div>
      </div>
    <% end %>
  </div>
</div>

ruby/homework/blog/app/views/categories/new.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>New Category</h1>
<%= form_with(model: @category) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path %>

ruby/homework/blog/app/views/categories/show.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<div class="container"
    <h1><%= @category.name %></h1>
    <p><%= @category.description %></p>
    <ul>

    <h2> Articles in <%= @category.name %> </h2>
    <% if @articles.present? %>
        <% @articles.each do |article| %>
            <div>
                <p><%= link_to article.title, article_path(article) %></p>
            </div>
        <% end %>
    <% else %>
        <p>No Articles Found in this Category</p>
    <%end%>
    <li><%= link_to "Edit Category", edit_category_path(@category) %></li>
    <li><%= link_to "Destroy Category", category_path(@category), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>

    </ul>
    <%= link_to 'Add Article', new_article_path(@category) %>
</div>