ruby/homework/blog/config/routes.rb
Rails.application.routes.draw do
  get "authors/new"
  get "authors/create"
  get "authors/show"
  get "authors/edit"
  get "authors/update"
  get "authors/destroy"
  devise_for :users
  get "donations/new"
  get "donations/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  



  resources :categories
    resources :authors

    resources :donations, only: [:new, :create]

    resources :articles do
      resources :comments, only: [:create, :destroy]  # Only allow create and destroy actions for comments
    end
    
  
  # Close the articles block
  # Close the categories block


  resources :donations, only: [:new, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "categories#index"
end

ruby/homework/blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    belongs_to :author

    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10}
    validates :author, presence: true
end

ruby/homework/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @category = Category.all
        @articles = Article.all
        @authors = Author.all
      end
      
  
      def show
        @article = Article.find(params[:id])   # Find the article by its id
      end
      
  
    def new
        @article = Article.new
    end
      
      
    def create
        @article = Article.new(article_params)
    
        if @article.save
          redirect_to @article
        else
          render :new, status: :unprocessable_entity
        end
    end
      
    
      
  
      def edit
        @article = Article.find(params[:id])
      end
      
  
    def update
      @article = Article.find(params[:id])
  
      if @article.update(article_params)
        redirect_to @article
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
  
      redirect_to root_path, status: :see_other
    end
  
    private
    
    # Strong parameters for article
      def article_params
        params.require(:article).permit(:title, :body, :category_id, :author_id)
      end
    
  end
  

ruby/homework/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/homework/blog/app/views/articles/_form.html.erb
<%= form_with(model: [@category, @article], local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, value: @article.title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :body, value: @article.body %>
  </div>

  <div>
      <%= form.label :author %><br>
      <%= form.collection_select :author_id, Author.all, :id, :name%> <br>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name%> 
    
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ruby/homework/blog/app/views/articles/edit.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>Edit Article</h1>

<%= render "form", article: @article %>

ruby/homework/blog/app/views/articles/index.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>Articles in <%= @category.name %></h1>



<ul>
<% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article_path(article) %> |
        <%= link_to 'Edit', edit_article_path(article) %>|
        <%= link_to 'Delete', article_path(@category, article), method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
<% end %>
</ul>

<%= link_to 'New Article', new_article_path(@category) %>

ruby/homework/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>
<br>
<%= link_to "Back to Articles", articles_path %>
 

ruby/homework/blog/app/views/articles/show.html.erb
<% content_for :javascript do %>
    <script type="module">
        import "article";
    </script>
<% end %>
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>

<div id="article-content">
    <h1><%= @article.title %></h1>
    <p><%= @article.body %></p>

    <p><strong>Author:</strong> 
    <% if @article.author.present? %>
        <%= @article.author.name %>
    <% else %>
        <em>Author not assigned</em>
    <% end %>
    </p>

    <ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Delete", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                    } %></li>
    </ul>

    <div id="comments">
    <h2>Comments</h2>
    <div id="initial-comments">
        <%= render @article.comments.limit(3) %> <!-- Show the first 3 comments -->
    </div>

    <button id="toggle-button">Show More Comments</button>

    <div id="additional-comments" style="display: none;">
        <%= render @article.comments.offset(3) %> <!-- Show the rest of the comments after the first 3 -->
    </div>

    <h2>Add a comment:</h2>
    <%= render "comments/form", article: @article %>
</div>
</div>