ruby/homework/blog/config/routes.rb
Rails.application.routes.draw do
  get "authors/new"
  get "authors/create"
  get "authors/show"
  get "authors/edit"
  get "authors/update"
  get "authors/destroy"
  devise_for :users
  get "donations/new"
  get "donations/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  



  resources :categories
    resources :authors

    resources :donations, only: [:new, :create]

    resources :articles do
      resources :comments, only: [:create, :destroy]  # Only allow create and destroy actions for comments
    end
    
  
  # Close the articles block
  # Close the categories block


  resources :donations, only: [:new, :create]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "categories#index"
end

ruby/homework/blog/app/models/author.rb
class Author < ApplicationRecord
    has_many :articles, dependent: :destroy

    validates :name, presence: true
    validates :bio, presence: true, length: {minimum: 10}
end

ruby/homework/blog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to author_path(@author), notice: 'Author was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to author_path(@author), notice: 'Author was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: 'Author was successfully deleted.'
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :bio)
  end
end

ruby/homework/blog/app/helpers/authors_helper.rb
module AuthorsHelper
end

ruby/homework/blog/app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: "Enter author name" %>
    </div>
  
    <div class="field">
      <%= form.label :bio %>
      <%= form.text_area :bio, placeholder: "Write a short bio" %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

ruby/homework/blog/app/views/authors/edit.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>Edit Author</h1>

<%= form_with(model: @author, local: true) do |form| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', author_path(@author) %>

ruby/homework/blog/app/views/authors/index.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>Authors</h1>

<%= link_to 'New Author', new_author_path %>

<ul>
  <% @authors.each do |author| %>
    <li>
      <%= link_to author.name, author_path(author) %> - 
      <%= truncate(author.bio, length: 50) %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back to Categories', categories_path %>

ruby/homework/blog/app/views/authors/new.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back to Authors', authors_path %>

ruby/homework/blog/app/views/authors/show.html.erb
<nav id="nav-links">
<%= link_to "Categories", categories_path %>
<%= link_to 'Authors', authors_path %>
<%= link_to 'All Articles', articles_path(@category) %>
<%= link_to 'Donations Page', donations_new_path %>
</nav>
<h1><%= @author.name %></h1>
<p><%= @author.bio %></p>

<h2>Articles by <%= @author.name %></h2>
<ul>
  <% if @articles.present? %>
    <% @articles.each do |article| %>
      <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
  <% else %>
    <li>No articles found for this author.</li>
  <% end %>
</ul>


<%= form_with(model: @author, method: :delete) do |form| %>
  <%= form.submit 'Delete', data: { confirm: 'Are you sure?' } %>
<% end %>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back to Authors', authors_path %>